version: "3.5"
services:

    app:
        build:
            context: .
            dockerfile: ./backend/app/Dockerfile
        restart: always
        volumes:
            - ./backend/app/code:/code
            - ./backend/uwsgi.log:/tmp/uwsgi.log
            - ./backend/app/socks:/tmp/socks
        secrets:
            - db_root_passwd
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: ./backend/db/Dockerfile
        restart: always
        volumes:
            - ./backend/db/data:/var/lib/mysql
        secrets:
            - db_root_passwd
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_passwd
            MYSQL_DATABASE: portal

    db-manager:
        build:
            context: .
            dockerfile: ./backend/db-manager/Dockerfile
        restart: always
        volumes:
            - ./backend/db/data:/var/lib/mysql
            - ./backend/db-manager/sessions:/sessions
        secrets:
            - db_root_passwd
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD_FILE: /run/secrets/db_root_passwd
            PMA_DATABASE: portal
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: ./frontend/web/Dockerfile
        restart: always
        volumes:
            - ./frontend/web/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/web/.htpasswd:/etc/nginx/.htpasswd
            - ./frontend/vue/dist:/usr/share/nginx/html
            - ./backend/app/socks:/tmp/socks
        networks:
            - caddynet
            - default
        labels:
            caddy: w2.kajitsu.dev
            caddy.reverse_proxy: "{{ upstreams 80 }}"
            caddy.tls: w2@kajitsu.dev

    vue-build:
        build:
            context: .
            dockerfile: ./frontend/vue-build/Dockerfile
        restart: always
        volumes:
            - ./frontend/vue:/vue
        networks:
            - caddynet
            - default
        labels:
            caddy: w2-dev.kajitsu.dev
            caddy.handle_path: /*
            caddy.handle_path.0_reverse_proxy: "{{ upstreams 8080 }}"
            caddy.tls: w2-dev@kajitsu.dev

secrets:
    db_root_passwd:
        file: ./backend/db/root_passwd

networks:
    caddynet:
        external: true