version: "3.5"
services:

    app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        restart: always
        volumes:
            - ./app/code:/code
            - ./uwsgi.log:/tmp/uwsgi.log
            - ./app/socks:/tmp/socks
        secrets:
            - db_root_passwd
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        restart: always
        volumes:
            - ./db/data:/var/lib/mysql
        secrets:
            - db_root_passwd
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_passwd
            MYSQL_DATABASE: portal

    db-manager:
        build:
            context: .
            dockerfile: ./db-manager/Dockerfile
        restart: always
        volumes:
            - ./db-manager/sessions:/sessions
        secrets:
            - db_root_passwd
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD_FILE: /run/secrets/db_root_passwd
            PMA_DATABASE: portal
        depends_on:
            - db

    web:
        build:
            context: .
            dockerfile: ./web/Dockerfile
        restart: always
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - ./web/.htpasswd:/etc/nginx/.htpasswd
            - ./vue/dist:/usr/share/nginx/html
            - ./app/socks:/tmp/socks
        networks:
            - caddynet
            - default
        labels:
            caddy: w2.kajitsu.dev
            caddy.reverse_proxy: "{{ upstreams 80 }}"
            caddy.tls: w2@kajitsu.dev

    vue-build:
        build:
            context: .
            dockerfile: ./vue-build/Dockerfile
        restart: always
        volumes:
            - ./vue:/vue

secrets:
    db_root_passwd:
        file: ./db/.root_passwd

networks:
    caddynet:
        external: true