version: "3.5"
services:

    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        restart: always
        volumes:
            - ./api/code:/code
        secrets:
            - db_root_passwd
        networks:
            - caddynet
            - default
        labels:
            caddy: w2.kajitsu.dev
            caddy.handle_path: /api/*
            caddy.handle_path.0_reverse_proxy: "{{ upstreams 80 }}"
            caddy.tls: w2@kajitsu.dev
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: ./db/Dockerfile
        restart: always
        volumes:
            - ./db/data:/var/lib/mysql
        secrets:
            - db_root_passwd
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_passwd
            MYSQL_DATABASE: portal
    
    db-manager:
        build:
            context: .
            dockerfile: ./db-manager/Dockerfile
        restart: always
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db-manager/sessions:/sessions
            - ./db-manager/.htaccess:/var/www/html/.htaccess
            - ./db-manager/.htpasswd:/var/www/html/.htpasswd
        secrets:
            - db_root_passwd
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD_FILE: /run/secrets/db_root_passwd
            PMA_DATABASE: portal
        networks:
            - caddynet
            - default
        labels:
            caddy: w2.kajitsu.dev
            caddy.handle_path: /db-manager/*
            caddy.handle_path.0_reverse_proxy: "{{ upstreams 80 }}"
            caddy.tls: w2@kajitsu.dev
        depends_on:
            - db

    portal:
        build:
            context: .
            dockerfile: ./portal/production/Dockerfile
        restart: always
        volumes:
            - ./portal/production/default.conf:/etc/nginx/conf.d/default.conf
            - ./portal/vue/dist:/usr/share/nginx/html
        networks:
            - caddynet
            - default
        labels:
            caddy: w2.kajitsu.dev
            caddy.handle_path: /portal/*
            caddy.handle_path.0_reverse_proxy: "{{ upstreams 80 }}"
            caddy.tls: w2@kajitsu.dev

    portal-dev:
        build:
            context: .
            dockerfile: ./portal/development/Dockerfile
        restart: always
        volumes:
            - ./portal/vue:/vue
        networks:
            - caddynet
            - default
        labels:
            caddy: w2-dev.kajitsu.dev
            caddy.handle_path: /*
            caddy.handle_path.0_reverse_proxy: "{{ upstreams 8080 }}"
            caddy.tls: w2-dev@kajitsu.dev

secrets:
    db_root_passwd:
        file: ./db/root_passwd

networks:
    caddynet:
        external: true
